### ISSUE TITLE
newest update (v2022.3.1) breaks the whole workspace

### ISSUE THREAD

**Issue by r4inX** [Servoy/svyKeyListener#12]
My colleague updatet the KeyListener, after that his workspace broke (error 404) so i just told him to delete the .metadata/.plugins\com.servoy.eclipse.ngclient.ui folder (which works everytime if we get a 404 build error)
But this time it didn´t work, so i tested it aswell. Same error. Even if i delete the keylistener from my solution and let the folder build again, same error 404. Below i will paste my build/error log.

```
./node_modules/@uppy/angular/fesm2015/uppy-angular.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string 'C:\workspaces_S21_PROD_NEW\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\@uppy\angular\fesm2015\uppy-angular.mjs: This application depends upon a library published using Angular version 14.1.3, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
49 | }
50 | DashboardComponent.Éµfac = i0.ÉµÉµngDeclareFactory({ minVersion: "12.0.0", version: "14.1.3", ngImport: i0, type: DashboardComponent, deps: [{ token: i0.ElementRef }], target: i0.ÉµÉµFactoryTarget.Component });
> 51 | DashboardComponent.Éµcmp = i0.ÉµÉµngDeclareComponent({ minVersion: "14.0.0", version: "14.1.3", type: DashboardComponent, selector: "uppy-dashboard", inputs: { uppy: "uppy", props: "props" }, usesInheritance: true, usesOnChanges: true, ngImport: i0, template: '', isInline: true, changeDetection: i0.ChangeDetectionStrategy.OnPush });
|                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
52 | i0.ÉµÉµngDeclareClassMetadata({ minVersion: "12.0.0", version: "14.1.3", ngImport: i0, type: DashboardComponent, decorators: [{
53 |             type: Component,
54 |             args: [{'
at run (C:\workspaces_S21_PROD_NEW\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\@babel\core\lib\transformation\index.js:37:15)
at run.next (<anonymous>)
at Function.transform (C:\workspaces_S21_PROD_NEW\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\@babel\core\lib\transform.js:25:41)
at transform.next (<anonymous>)
at step (C:\workspaces_S21_PROD_NEW\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\gensync\index.js:261:32)
at C:\workspaces_S21_PROD_NEW\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\gensync\index.js:273:13
at async.call.result.err.err (C:\workspaces_S21_PROD_NEW\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\gensync\index.js:223:11)
at C:\workspaces_S21_PROD_NEW\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\gensync\index.js:37:40

Error: node_modules/@uppy/angular/lib/components/dashboard-modal/dashboard-modal.component.d.ts:17:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

17     static Éµcmp: i0.ÉµÉµComponentDeclaration<DashboardModalComponent, "uppy-dashboard-modal", never, { "uppy": "uppy"; "props": "props"; "open": "open"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@uppy/angular/lib/components/dashboard/dashboard.component.d.ts:15:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

15     static Éµcmp: i0.ÉµÉµComponentDeclaration<DashboardComponent, "uppy-dashboard", never, { "uppy": "uppy"; "props": "props"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@uppy/angular/lib/components/drag-drop/drag-drop.component.d.ts:15:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

15     static Éµcmp: i0.ÉµÉµComponentDeclaration<DragDropComponent, "uppy-drag-drop", never, { "uppy": "uppy"; "props": "props"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@uppy/angular/lib/components/progress-bar/progress-bar.component.d.ts:15:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

15     static Éµcmp: i0.ÉµÉµComponentDeclaration<ProgressBarComponent, "uppy-progress-bar", never, { "uppy": "uppy"; "props": "props"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@uppy/angular/lib/components/status-bar/status-bar.component.d.ts:15:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

15     static Éµcmp: i0.ÉµÉµComponentDeclaration<StatusBarComponent, "uppy-status-bar", never, { "uppy": "uppy"; "props": "props"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jcompagner** [comment]
This has noting todo with the keylistener.
But with servoy extra: 
https://github.com/Servoy/servoy-extra-components/releases/tag/v2022.6.4
or
https://github.com/Servoy/servoy-extra-components/releases/tag/v2022.3.6

you need to update servoy extra
